# Generated by Django 5.1.3 on 2025-04-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_instrument_current_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['ticker'], name='instruments_ticker_c99931_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['type'], name='instruments_type_953021_idx'),
        ),
    ]
