# Generated by Django 5.1.3 on 2025-04-29 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_instrument_instruments_ticker_c99931_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='The current market price per unit of the instrument.', max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(blank=True, help_text='The unique ticker symbol of the instrument.', max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
