# Generated by Django 5.1.3 on 2025-04-29 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
