# Generated by Django 5.1.3 on 2024-11-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_balance'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='instruments.instrument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.profile')),
            ],
        ),
    ]
