# Generated by Django 5.1.3 on 2024-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_investment_avg_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
