# Generated by Django 5.1.3 on 2024-12-11 19:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_investment_instrument_alter_investment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
    ]
