# Generated by Django 5.1.3 on 2025-04-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_balance'),
        ('common', '0005_alter_investment_avg_price_and_more'),
        ('instruments', '0006_instrument_instruments_ticker_c99931_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_instances', to='instruments.instrument'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', 0)), name='investment_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('avg_price__gte', 0)), name='investment_price_non_negative'),
        ),
    ]
